#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

# START handling initial database fixtures
# Check if the setup_complete flag is set to True. If not, apply initial fixtures once
# Capture the output of the Python script into a variable
SETUP_STATUS=$(python manage.py shell -c "from backend_django.config.models import SetupFlag; \
  print('true') if SetupFlag.objects.filter(setup_complete=True).exists() else print('false')")
# Check the value of the variable
if [ "$SETUP_STATUS" = "false" ]; then
  echo "Initial setup flag not found. Running data load of initial db fixtures...."
  # Load fixtures - for production we skip those with a prefix of dev_...
  find ./fixtures -name '*.json' ! -name 'dev_*' -print0 | xargs -0 -r python manage.py loaddata
  # After successfully loading data, create the flag in the database
  # to prevent this block from running again.
  echo "Marking setup as complete."
  python manage.py shell -c "from backend_django.config.models import SetupFlag; \
    SetupFlag.objects.create(setup_complete=True)"

else
  echo "Initial setup flag found. Skipping data load of db fixtures."
fi
# END handling initial database fixtures

python manage.py create_or_update_superuser   # env variables need to be set !
python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
