#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python backend_django/manage.py migrate
/seed_fixtures.sh --guard --exclude-dev
python backend_django/manage.py create_or_update_superuser
python /app/backend_django/manage.py collectstatic --noinput
/usr/local/bin/gunicorn backend_django.config.wsgi --bind 0.0.0.0:5000 --chdir=/app
