#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python backend_django/manage.py makemigrations
python backend_django/manage.py migrate
/seed_fixtures.sh --guard
python backend_django/manage.py create_or_update_superuser
python backend_django/manage.py runserver_plus 0.0.0.0:5000
