#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py runserver_plus 0.0.0.0:5000
#python manage.py runserver_plus --cert-file cert/cert.pem --key-file cert/key.pem  0.0.0.0:5000
